<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtimeToRdbmsMapping" nsURI="http://blackbelt.hu/judo/meta/runtime/rdbms/mapping"
    nsPrefix="runtimeToRdbms">
  <eClassifiers xsi:type="ecore:EClass" name="Mappings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rdbmsType" lowerBound="1"
        eType="ecore:EClass http://blackbelt.hu/judo/meta/psm/rdbms#//RdbmsFieldType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
