<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sabre" nsURI="http://blackbelt.hu/sabre/schema" nsPrefix="sabre">
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="xsString" literal="xs:string"/>
    <eLiterals name="xsInt" value="1" literal="xs:int"/>
    <eLiterals name="xsFloat" value="2" literal="xs:float"/>
    <eLiterals name="xsDate" value="3" literal="xs:date"/>
    <eLiterals name="xsDateTime" value="4" literal="xs:dateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitive" upperBound="-1"
        eType="#//primitive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//list"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" upperBound="-1"
        eType="#//structure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" upperBound="-1"
        eType="#//template" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="list">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="#//structure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitive" eType="#//primitive"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="primitive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitive" upperBound="-1"
        eType="#//primitive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//list"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" upperBound="-1"
        eType="#//structure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" upperBound="-1"
        eType="#//template" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="xsString" literal="xs:string"/>
    <eLiterals name="xsInt" value="1" literal="xs:int"/>
    <eLiterals name="xsFloat" value="2" literal="xs:float"/>
    <eLiterals name="xsDate" value="3" literal="xs:date"/>
    <eLiterals name="xsDateTime" value="4" literal="xs:dateTime"/>
  </eClassifiers>
</ecore:EPackage>
